from pathlib import Path
from html import escape
from hashlib import sha256

ROOT=Path(__file__).resolve().parents[1]
DIST=ROOT/'dist'
ORIGIN='https://withso.com'
COMPANY='Withso Technologies (OPC) Private Limited'
EMAIL='contact@withso.com'
def asset_url(path):
    digest=sha256((DIST/path.lstrip('/')).read_bytes()).hexdigest()[:12]
    return path+'?v='+digest

LOGO=f'<img class="brand-logo" src="{asset_url("/assets/withso-logo.svg")}" width="871" height="217" alt="Withso">'
FAVICONS=(
    f'<link rel="icon" type="image/x-icon" href="{asset_url("/favicon.ico")}">'
    f'<link rel="icon" type="image/png" sizes="32x32" href="{asset_url("/assets/favicon-32.png")}">'
    f'<link rel="icon" type="image/png" sizes="16x16" href="{asset_url("/assets/favicon-16.png")}">'
    f'<link rel="apple-touch-icon" sizes="180x180" href="{asset_url("/assets/apple-touch-icon.png")}">'
)

def link(path,text,css='text-link',external=False):
    return f'<a class="{css}" href="{escape(path,quote=True)}"'+(' target="_blank" rel="noopener noreferrer"' if external else '')+f'>{text}</a>'

def mail(text='Talk to us',css='button'):
    return link('mailto:'+EMAIL,text,css)

def eyebrow(text):return f'<div class="eyebrow">{text}</div>'

def header(route):
    items=[('/mapsmith','Mapsmith'),('/jurisfield','JurisField'),('/about','Company')]
    nav=''.join(f'<a href="{u}"'+(' aria-current="page"' if route==u else '')+f'>{label}</a>' for u,label in items)
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="container nav"><a href="/" class="brand" aria-label="Withso home">{LOGO}</a><button class="menu-button" type="button" aria-expanded="false" aria-controls="main-navigation"><span>Menu</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 8h16M4 16h16" stroke="currentColor" stroke-width="1.5"/></svg></button><nav class="nav-links" id="main-navigation" aria-label="Main navigation">{nav}<a class="nav-contact" href="mailto:{EMAIL}">Get in touch</a></nav></div></header>'''

def footer():
    return f'''<footer class="site-footer"><div class="container"><div class="footer-main"><div class="footer-brand"><a href="/" class="brand" aria-label="Withso home">{LOGO}</a><p>Geospatial software.<br>Built in India, for the world.</p></div><div class="footer-links"><div class="footer-column"><strong>Products</strong><a href="/mapsmith">Mapsmith</a><a href="/jurisfield">JurisField</a></div><div class="footer-column"><strong>Initiatives</strong><a href="https://nammatn.in/" target="_blank" rel="noopener noreferrer">NammaTN</a><a href="/#zeros">Zeros</a></div><div class="footer-column"><strong>Company</strong><a href="/about">About Withso</a><a href="mailto:{EMAIL}">Contact</a></div></div></div><div class="footer-bottom"><div class="footer-company">© 2026 {COMPANY}. All rights reserved.<br>Chennai, India · CIN U74103TN2025OPC177570</div><div class="footer-legal"><a href="/privacy">Privacy policy</a><a href="/terms">Terms &amp; conditions</a></div></div></div></footer>'''

def page(route,title,description,body):
    canonical=ORIGIN+route
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><title>{escape(title)}</title><meta name="description" content="{escape(description,quote=True)}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="Withso"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="{canonical}"><meta name="twitter:card" content="summary">{FAVICONS}<link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body>{header(route)}<main id="main">{body}</main>{footer()}</body></html>'''
    path=DIST/'index.html' if route=='/' else DIST/route.lstrip('/')/'index.html'
    path.parent.mkdir(parents=True,exist_ok=True);path.write_text(html)

# Schematic sample geospatial layers. These are illustrative data, not a geographic basemap.
def map_canvas(kind='forest',small=False):
    points={'forest':[(112,115),(226,93),(342,164),(264,226),(415,70)],'assets':[(90,184),(177,165),(257,117),(337,88),(385,193),(290,257)],'civic':[(127,118),(225,152),(302,214),(387,124)]}
    dots=''.join(f'<circle cx="{x}" cy="{y}" r="5" fill="#66816f" stroke="#fff" stroke-width="2"/>' for x,y in points[kind])
    svg=f'''<svg viewBox="0 0 500 320" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="500" height="320" fill="#eff3ed"/><path d="M0 0H194L168 63 212 108 190 180 140 205 152 265 92 320H0Z" fill="#e1eadc"/><path d="M209 0H427L391 52 429 111 397 167 413 223 341 236 316 320H168L206 270 174 215 232 179 240 108 199 54Z" fill="#e4ecdF"/><path d="M427 0 391 52 429 111 397 167 413 223 341 236 316 320H500V0Z" fill="#e9efe4"/><g fill="none" stroke="#c1d1c0" stroke-width="1.1"><path d="M194 0 168 63 212 108 190 180 140 205 152 265 92 320M427 0 391 52 429 111 397 167 413 223 341 236 316 320M199 54 272 67 333 39 391 52M232 179 300 166 353 182 397 167M174 215 255 242 341 236M240 108 310 109 349 135 429 111"/></g><path d="M-20 252C42 218 78 254 122 216S199 167 228 190 263 138 303 150 351 110 383 131 451 73 520 90" fill="none" stroke="#cfdee6" stroke-width="14"/><path d="M-20 252C42 218 78 254 122 216S199 167 228 190 263 138 303 150 351 110 383 131 451 73 520 90" fill="none" stroke="#b8cfdc" stroke-width="1"/><g fill="none" stroke="#fff" stroke-width="5"><path d="M55-15 92 75 168 104 207 163 268 193 329 225 360 340M-10 88 86 107 166 138 206 164 296 97 401 54 520 38M30 340 115 276 206 261 268 193 391 190 530 241"/></g><g fill="none" stroke="#d5dcd2" stroke-width=".8"><path d="M55-15 92 75 168 104 207 163 268 193 329 225 360 340M-10 88 86 107 166 138 206 164 296 97 401 54 520 38M30 340 115 276 206 261 268 193 391 190 530 241"/></g><g fill="none" stroke="#abbfad" stroke-width="1.2" stroke-dasharray="4 5"><path d="M66 48 196 43 225 89 194 166 113 184 58 126Z"/><path d="M274 86 370 66 413 115 393 197 309 215 252 163Z"/></g>{dots}</svg>'''
    labels='' if small else '<span class="map-label" style="top:21%;left:19%">North block</span><span class="map-label" style="top:68%;left:60%">South block</span><div class="map-tools" aria-hidden="true"><span>+</span><span>−</span></div><div class="map-key"><span><i></i>Field records</span><span><i class="blue"></i>Water</span></div>'
    return f'<div class="map-canvas" aria-hidden="true">{svg}{labels}</div>'

def map_workspace():
    return f'''<div class="workspace" aria-hidden="true"><div class="workspace-top"><span class="workspace-brand">Mapsmith</span><span>Forest management</span><span class="project-chip">Published map</span></div><div class="workspace-body"><div class="layers"><div class="tiny-label">Layers</div><div class="layer-item"><i class="layer-swatch"></i>Work areas</div><div class="layer-item"><i class="layer-swatch"></i>Forest boundaries</div><div class="layer-item"><i class="layer-swatch blue"></i>Water bodies</div><div class="layer-item"><i class="layer-swatch dot"></i>Field records</div><div class="tiny-label" style="margin-top:29px">Map settings</div><div class="layer-item">Basemap · Light</div><div class="layer-item">Workspace access</div></div>{map_canvas()}</div></div>'''

def phone():
    return f'''<div class="phone" aria-hidden="true"><div class="phone-top"><span>9:41</span><span>Offline ready</span></div><h4>JurisField</h4>{map_canvas(small=True)}<div class="phone-record"><strong>Field inspection</strong>North block · Assigned area<br>Location recorded</div><div class="phone-action">Capture record</div></div>'''

def field_dashboard():
    return '''<div class="workspace field-dashboard" aria-hidden="true"><div class="workspace-top"><span class="workspace-brand">JurisField</span><span>Workspace</span><span class="project-chip">Office review</span></div><div class="workspace-body"><div><div class="assignment-title">Field assignments</div><div class="mini-row"><span>North block inspection</span><span class="mini-status">Submitted</span></div><div class="mini-row"><span>Water body survey</span><span class="mini-status">In progress</span></div><div class="mini-row"><span>Boundary verification</span><span class="mini-status">Ready</span></div><div class="mini-row"><span>Location · Evidence · Review</span></div></div></div></div>'''

def visual(inside,css='mist',hero=False):
    return f'<div class="visual-stage {css}'+(' hero-product-preview' if hero else '')+f'">{inside}<span class="visual-label">Illustrative workspace</span></div>'

def cta(title,description):
    return f'<div class="container"><section class="cta-section reveal"><div><h2>{title}</h2><p>{description}</p></div>{mail()}</section></div>'

home=f'''<div class="container"><section class="hero"><div class="reveal">{eyebrow('Independent software company · Chennai, India')}<h1>Geospatial software.<span class="hero-line">Real-world impact.</span></h1><div class="hero-bottom"><p>We build software that connects maps, data and fieldwork. Meet Mapsmith and JurisField.</p><div class="hero-meta">Built in India <span></span> Made for the world</div></div></div></section><section class="section" id="products"><div class="section-head reveal"><div>{eyebrow('Our core products')}<h2>From spatial data<br>to work on the ground.</h2></div><p>Two focused products.<br>One geospatial foundation.</p></div><div class="products-grid"><article class="product reveal">{visual(map_workspace())}<div class="product-heading"><h3 class="product-name"><img src="/assets/mapsmith.svg" alt="" width="27" height="27">Mapsmith</h3><span class="product-category">Geospatial platform</span></div><p class="product-desc">Publish spatial data, build maps and run analysis. A programmable GIS platform on your infrastructure.</p>{link('/mapsmith','Explore Mapsmith')}</article><article class="product reveal">{visual('<div class="field-home-layout">'+field_dashboard()+phone()+'</div>','field')}<div class="product-heading"><h3 class="product-name"><img src="/assets/jurisfield.svg" alt="" width="27" height="27">JurisField</h3><span class="product-category">Field operations</span></div><p class="product-desc">Turn maps and forms into offline-ready assignments. Bring field records back with location and evidence intact.</p>{link('/jurisfield','Explore JurisField')}</article></div></section><section class="section company-section reveal">{eyebrow('Our company')}<div><h2>Useful software begins<br>with a real problem.</h2><p>Withso is a product company focused on geospatial technology. We develop our own platforms and build custom GIS applications for organisations working with places, people and public systems.</p>{link('/about','About Withso')}</div></section><section class="section initiative-grid"><article class="initiative-card reveal">{eyebrow('Social impact')}<h3>NammaTN</h3><p>An independent civic platform for Tamil Nadu. Report local issues, verify them as a community and track public follow-through.</p>{link('https://nammatn.in/','Visit NammaTN',external=True)}</article><article class="initiative-card quiet reveal" id="zeros">{eyebrow('Beyond geospatial')}<h3>Zeros</h3><p>Our AI orchestrator platform. A native macOS workspace for coordinating parallel coding agents and reviewing their work.</p>{mail('Enquire about Zeros','text-link')}</article></section></div>{cta('Have a geospatial challenge?','Let’s talk about the software your work needs.')}'''
page('/','Withso — Geospatial software. Real-world impact.','Withso builds Mapsmith and JurisField: GIS platforms, spatial analysis and field operations software. Based in Chennai, India. Home of NammaTN and Zeros.',home)


def data_preview():
    return '''<div class="data-preview" aria-hidden="true"><h4>Your spatial data, in one place</h4><div class="data-file"><div class="file-icon">GIS</div><div class="file-info">Forest boundaries<small>Spatial layer · Polygons</small></div><span class="file-state">Published</span></div><div class="data-file"><div class="file-icon">GIS</div><div class="file-info">Water bodies<small>Spatial layer · Polygons</small></div><span class="file-state">Published</span></div><div class="data-file"><div class="file-icon">GIS</div><div class="file-info">Field observations<small>Spatial layer · Points</small></div><span class="file-state">Published</span></div><div class="data-foot"><span>PostGIS-backed services</span><span>Workspace access</span></div></div>'''

def analysis_preview():
    return f'''<div class="data-preview" aria-hidden="true"><h4>Spatial analysis · Example output</h4><div class="mock-stats"><div class="mock-stat"><strong>06</strong><span>Work areas</span></div><div class="mock-stat"><strong>24</strong><span>Survey locations</span></div><div class="mock-stat"><strong>03</strong><span>Priority zones</span></div></div><div class="mock-chart">{''.join('<div class="bar" style="--height:'+str(h)+'%"></div>' for h in [33,57,44,80,68,92])}</div><div class="bar-labels"><span>A</span><span>B</span><span>C</span><span>D</span><span>E</span><span>F</span></div><div class="data-foot"><span>Records by work area</span><span>Sample data</span></div></div>'''

def code_preview():
    return '''<div class="code-preview" aria-hidden="true"><div class="code-head"><span>Mapsmith · Programmable GIS</span><span>API / CLI</span></div><pre><span class="code-comment"># A spatial workflow</span>\nConnect your spatial data\n  <span class="code-accent">PostGIS</span> → layers\n\nAuthor maps and run analysis\n  layers → <span class="code-accent">maps + results</span>\n\nPublish to your applications\n  <span class="code-accent">API · CLI · Your infrastructure</span></pre></div>'''

def feature(n,title,text,inside,tags,reverse=False,blue=False):
    return f'<section class="feature-row'+(' reverse' if reverse else '')+f' reveal"><div class="feature-visual'+(' blue' if blue else '')+f'">{inside}<span class="visual-label">Illustrative workspace</span></div><div class="feature-copy"><div class="feature-number">{n:02}</div><h2>{title}</h2><p>{text}</p><div class="feature-list">'+''.join(f'<span>{t}</span>' for t in tags)+'</div></div></section>'

def use_cases(product):
    data=[('forestry','Forestry & conservation','See the landscape.<br>Coordinate the work.','Bring boundaries, water bodies and field observations into one spatial view.','forest'),('infrastructure','Infrastructure','Keep assets<br>in context.','Map infrastructure and connect inspection records to the assets and areas they belong to.','assets'),('public','Public programmes','Put location<br>behind each decision.','Organise local information by work area and make spatial records useful to programme teams.','civic')]
    if product=='jurisfield':
        data=[('inspections','Field inspections','Every record,<br>with its context.','Give field teams an assigned area and capture observations with location and supporting evidence.','forest'),('surveys','Asset surveys','Know what is there.<br>Know where it is.','Collect structured records and geometry for assets, boundaries and local infrastructure.','assets'),('programmes','Public programmes','A connected workflow<br>from office to field.','Prepare assignments in the office, collect offline and review submissions in their work area.','civic')]
    tabs='';panels=''
    for i,(key,label,title,text,kind) in enumerate(data):
        key=product+'-'+key
        tabs+=f'<button class="use-case-tab" type="button" role="tab" id="tab-{key}" aria-controls="panel-{key}" aria-selected="'+('true' if i==0 else 'false')+f'" tabindex="{0 if i==0 else -1}">{label}</button>'
        panels+=f'<div class="use-case-panel" role="tabpanel" id="panel-{key}" aria-labelledby="tab-{key}" tabindex="0"'+(' hidden' if i else '')+f'><div><span class="use-case-context">Example workflow</span><h3>{title}</h3><p>{text}</p></div>{map_canvas(kind)}</div>'
    return f'<section class="use-cases reveal">{eyebrow("Where it fits")}<h2>Built around real work.</h2><div class="use-case-layout" data-tabs><div class="use-case-tabs" role="tablist" aria-label="{product.capitalize()} use cases">{tabs}</div><div>{panels}</div></div></section>'

check='<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m4 10 4 4 8-8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>'
def strip(items):return '<div class="product-strip">'+''.join(f'<span>{check}{x}</span>' for x in items)+'</div>'

mapsmith=f'''<div class="container"><section class="product-hero">{eyebrow('Mapsmith · Geospatial platform')}<h1>Your spatial data.<br>A clearer picture.</h1><p>Publish layers, build maps and run geospatial analysis. A programmable GIS platform that stays in your control.</p><div class="actions">{link('https://mapsmith.santhoshbalaji.cloud/','Visit Mapsmith','button',True)}{mail('Discuss your use case','button secondary')}</div></section>{visual(map_workspace(),hero=True)}{strip(['Spatial data publishing','Map authoring','Geospatial analysis','Self-hosted control'])}{feature(1,'Put your spatial data<br>to work.','Publish spatial layers through PostGIS-backed services. Give your organisation a shared foundation for maps and applications.',data_preview(),['Spatial layers','PostGIS','Publishing'])}{feature(2,'Build the map<br>your team needs.','Bring layers together, shape the view and author maps around your work. Keep the important information in its geographic context.',map_workspace(),['Map authoring','Layers','MapLibre'],reverse=True,blue=True)}{feature(3,'Turn location<br>into answers.','Run geospatial operations and explore the relationships in your data. Use spatial analysis to support planning and day-to-day decisions.',analysis_preview(),['Spatial analysis','Geoprocessing','Planning'])}{feature(4,'Your infrastructure.<br>Your control.','Self-host the platform and automate workflows through APIs and a CLI. Build GIS into your applications with a programmable core.',code_preview(),['Self-hosted','APIs & CLI','Application integration'],reverse=True,blue=True)}{use_cases('mapsmith')}<section class="section company-section reveal">{eyebrow('The field connection')}<div><h2>Take the next step<br>into the field.</h2><p>JurisField gives field teams assigned work areas, offline collection and records with evidence. Explore the field operations side of Withso.</p>{link('/jurisfield','Explore JurisField')}</div></section></div>{cta('Make your spatial data useful.','Tell us what you want to publish, analyse or build.')}'''
page('/mapsmith','Mapsmith — Geospatial platform | Withso','Publish spatial data, author maps, run geospatial analysis and automate through APIs and a CLI. Mapsmith is Withso’s self-hosted GIS platform.',mapsmith)

def record_preview():
    return '''<div class="record-preview" aria-hidden="true"><div class="record-heading"><span>Field inspection · Sample record</span><span class="project-chip">Submitted</span></div><div class="record-detail"><div><span>Work area</span>North block</div><div><span>Location</span>Captured with record</div><div><span>Evidence</span>Watermarked photograph</div><div><span>Collection</span>Native field app</div></div><div class="evidence-strip"><span class="evidence-icon">✓</span><span>Location · Timestamp · Evidence policy</span></div><div class="record-verification"><span>Original context preserved</span><span>Ready for review</span></div></div>'''

def offline_preview():
    return '''<div class="offline-preview" aria-hidden="true"><h4>Offline work packs</h4><div class="pack"><div class="pack-title"><strong>North block</strong><span class="pack-check">✓</span></div><small>Work area · Layers · Assignment</small><div class="pack-progress"></div></div><div class="pack"><div class="pack-title"><strong>Water body survey</strong><span class="pack-check">✓</span></div><small>Prepared for field collection</small><div class="pack-progress"></div></div><div class="sync-row"><span>Capture without a connection</span><span>Sync when online</span></div></div>'''

jurisfield=f'''<div class="container"><section class="product-hero">{eyebrow('JurisField · Field operations')}<h1>Work in the field.<br>Keep the full picture.</h1><p>Turn layers, forms and work areas into offline-ready assignments. Bring every record back with location and evidence intact.</p><div class="actions">{link('https://jurisfield.com/','Visit JurisField','button',True)}{mail('Discuss your use case','button secondary')}</div></section><div class="visual-stage field field-hero-preview">{field_dashboard()}{phone()}<span class="visual-label">Illustrative workspace</span></div>{strip(['Web workspace','Native iOS & Android','Offline collection','Evidence & review'])}{feature(1,'Give every task<br>a place to belong.','Publish GIS hierarchies, define work areas and assign fieldwork. Resolve jurisdiction from GPS or a selected location.',map_workspace().replace('Mapsmith','JurisField').replace('Forest management','Work areas'),['GIS hierarchies','Assignments','Jurisdiction'])}{feature(2,'Keep working.<br>Even offline.','Prepare offline packs before a visit. Collect records without a connection, then sync queued captures when you are back online.',offline_preview(),['Offline packs','Native apps','Queued sync'],reverse=True,blue=True)}{feature(3,'Capture evidence<br>with context.','Record observations, geometry and photographs against an assignment. Permanent photo watermarks keep location and capture details visible.',record_preview(),['Geometry & forms','Watermarked photos','Capture context'])}{feature(4,'Bring the field<br>back to the office.','Review submissions in their work area, with records and supporting evidence together. Keep a clear trail from assignment to review.',field_dashboard(),['Office review','Field records','Traceable workflow'],reverse=True,blue=True)}{use_cases('jurisfield')}<section class="section reveal">{eyebrow('One connected workflow')}<h2>Prepare. Capture. Review.</h2><div class="how-it-works"><div class="workflow-step"><div class="feature-number">01</div><h3>Prepare in the office</h3><p>Define layers, forms, work areas and assignments in your web workspace.</p></div><div class="workflow-step"><div class="feature-number">02</div><h3>Capture in the field</h3><p>Use the native app to collect records and evidence, online or offline.</p></div><div class="workflow-step"><div class="feature-number">03</div><h3>Review in context</h3><p>Sync submissions and review every record with its location and evidence.</p></div></div></section></div>{cta('Make fieldwork part of your GIS.','Let’s discuss your team, work areas and evidence needs.')}'''
page('/jurisfield','JurisField — Field operations & trusted GIS records | Withso','Offline-ready field assignments, jurisdiction lookup, native iOS and Android apps, watermarked photographs and office review. Meet JurisField by Withso.',jurisfield)

about=f'''<div class="container"><section class="hero">{eyebrow('About Withso')}<h1>Built around places.<br><span class="hero-line">Focused on people.</span></h1><div class="hero-bottom"><p>We build practical software for geospatial work, field operations and civic participation.</p><div class="hero-meta">Chennai, India</div></div></section><section class="about-grid section reveal"><h2>A product company<br>with a geospatial core.</h2><div><p>Withso develops its own software products, with Mapsmith and JurisField at the centre of our work. Our focus is simple: make spatial data easier to publish, understand and use in the real world.</p><p>We also build custom GIS applications for organisations. Our work connects product engineering with the practical needs of public systems and field teams.</p><p>Our product engineering is led by Santhosh Balaji S, whose experience spans software products and public-sector GIS systems.</p>{link('https://santhoshbalaji.cloud/','Meet our product builder',external=True)}</div></section><section class="section reveal">{eyebrow('What we build')}<div class="about-products"><article class="about-product"><h3>Mapsmith</h3><p>A self-hosted geospatial platform for spatial data, maps, analysis and programmable workflows.</p>{link('/mapsmith','Explore Mapsmith')}</article><article class="about-product"><h3>JurisField</h3><p>A field operations platform for assignments, offline records, location and supporting evidence.</p>{link('/jurisfield','Explore JurisField')}</article><article class="about-product"><h3>NammaTN</h3><p>Our independent social impact initiative for civic reporting and public transparency in Tamil Nadu.</p>{link('https://nammatn.in/','Visit NammaTN',external=True)}</article><article class="about-product"><h3>Zeros</h3><p>Our AI orchestrator platform for coordinating parallel coding agents in a native macOS workspace.</p>{mail('Enquire about Zeros','text-link')}</article></div></section><section class="section reveal">{eyebrow('Company information')}<h2>Withso, officially.</h2><dl class="company-details"><div><dt>Legal name</dt><dd>{COMPANY}</dd></div><div><dt>Corporate identity number</dt><dd>U74103TN2025OPC177570</dd></div><div><dt>Registered office</dt><dd>766, Tower 1, Shakti Towers, Ground Floor,<br>Anna Salai, Chennai, India – 600002</dd></div><div><dt>Company</dt><dd>Incorporated in India · 2025</dd></div><div><dt>Contact</dt><dd><a class="text-link" href="mailto:{EMAIL}">{EMAIL}</a></dd></div></dl><p>Withso is an independently operated software company incorporated in India. NammaTN is an independent civic initiative.</p></section></div>{cta('Let’s build something useful.','For product enquiries, GIS projects and partnerships.')}'''
page('/about','About Withso — Company & products','Withso Technologies (OPC) Private Limited is a Chennai-based software company focused on Mapsmith, JurisField, geospatial development and civic technology.',about)

privacy=f'''<div class="container legal-page">{eyebrow('Website policy')}<h1>Privacy policy</h1><p class="legal-meta">Last updated · 7 October 2026</p><p class="intro">This policy covers this Withso company website, operated by {COMPANY}. Product accounts, field records and other in-product data are covered by the notices and policies of the relevant product.</p><h2>Browsing this website</h2><p>This website presents company and product information. It does not require an account, collect form submissions, or include advertising, behavioural analytics or tracking scripts.</p><p>Our hosting provider may process technical information, including IP addresses, browser details and request logs, to deliver and secure the website. Hosting access controls may use essential session cookies.</p><h2>When you contact us</h2><p>If you email us, we receive your email address and the information you send. We use it to respond to your enquiry and maintain the relevant business correspondence. Please share only information needed for your enquiry.</p><h2>Product websites and external links</h2><p>Links to Mapsmith, JurisField, NammaTN and other websites take you to separate services. Their privacy notices explain how those services handle information. This website’s policy does not replace them.</p><h2>Sharing and retention</h2><p>We do not sell personal information collected through correspondence. We share it only with service providers needed to handle the enquiry, where you request it, or when required by law. We retain correspondence for the enquiry, an ongoing business relationship, and any applicable legal obligations.</p><h2>Your requests</h2><p>For privacy questions or requests concerning information in our correspondence, email <a href="mailto:{EMAIL}">{EMAIL}</a>. We will respond as required by applicable law. For product data requests, please use the contact information in that product’s privacy notice.</p><h2>Changes and contact</h2><p>We will update the date on this page when this website policy changes.</p><p>{COMPANY}<br>CIN: U74103TN2025OPC177570<br>766, Tower 1, Shakti Towers, Ground Floor, Anna Salai,<br>Chennai, India – 600002<br><a href="mailto:{EMAIL}">{EMAIL}</a></p></div>'''
page('/privacy','Privacy policy | Withso','How Withso’s company website handles technical information, email correspondence, external links and privacy requests.',privacy)

terms=f'''<div class="container legal-page">{eyebrow('Website terms')}<h1>Terms &amp; conditions</h1><p class="legal-meta">Last updated · 7 October 2026</p><p class="intro">These terms apply to this company website, operated by {COMPANY}. Please read them alongside our <a href="/privacy">Privacy policy</a>.</p><h2>Using this website</h2><p>You may browse this website and use its information for lawful purposes. You must not interfere with its operation, attempt unauthorised access, distribute malicious content or infringe the rights of others.</p><h2>Product information</h2><p>This website introduces our products and work. Product availability, features and commercial terms may change. A product’s own terms, privacy policy and any written agreement govern use of that product. Illustrative workspaces use sample data and are not live product sessions.</p><h2>Copyright and intellectual property</h2><p>The website’s original text, design and brand assets belong to Withso or their respective owners. You may link to these pages and refer to our products with attribution. These terms do not grant a licence to our software or permit unauthorised redistribution of our content. Third-party names belong to their respective owners.</p><h2>External services</h2><p>Links may open separate websites. Those services operate under their own terms and policies. Providing a link does not create a guarantee about their availability or content.</p><h2>Availability and liability</h2><p>We aim to keep this website accurate and available, but provide its information as available, without a guarantee of uninterrupted service or suitability for a particular purpose. Nothing in these terms excludes liability or rights that cannot lawfully be excluded.</p><h2>Applicable law</h2><p>These website terms are governed by the laws of India. Any applicable mandatory rights remain in place.</p><h2>Changes and contact</h2><p>We may revise these terms by publishing an updated version and date on this page. For website enquiries or copyright concerns, contact <a href="mailto:{EMAIL}">{EMAIL}</a>.</p><p>{COMPANY}<br>CIN: U74103TN2025OPC177570<br>766, Tower 1, Shakti Towers, Ground Floor, Anna Salai,<br>Chennai, India – 600002</p></div>'''
page('/terms','Terms & conditions | Withso','Terms for using Withso’s company website, product information, original content and external links.',terms)

# Legacy paths keep company policy links usable when moving the domain.
for old,new in [('/legal/privacy-policy','/privacy'),('/legal/terms','/terms')]:
    src=DIST/new.lstrip('/')/'index.html';dest=DIST/old.lstrip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(src.read_text())
page('/404','Page not found | Withso','This page could not be found. Explore Withso, Mapsmith and JurisField.',f'<div class="container notfound">{eyebrow("Withso")}<h1>Page not found.</h1><p>The page may have moved. Explore our products from the homepage.</p>{link("/","Back to Withso","button")}</div>')
(DIST/'404.html').write_text((DIST/'404/index.html').read_text())
(DIST/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n')
(DIST/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+r+'</loc></url>' for r in ['/','/mapsmith','/jurisfield','/about','/privacy','/terms'])+'</urlset>')
print('Generated homepage, 2 product pages, About, Privacy, Terms, legacy policy paths and 404.')
